### ISSUE TITLE
Make p check out code repositories automatically

### ISSUE THREAD

**Issue by HerrSubset** [deVinnnie/dotfiles#1]
Currently, the  `p` command only moves to a new directory. If you don't have the project, bad luck. It would be *super awesome* if p would be able to autmatically check out a code repo in case you didn't have it yet.

Proposed approach:
 * use a ~/.prc file that just list urls of accessible repositories
 * create a python script that uses [beautifulsoup](https://www.crummy.com/software/BeautifulSoup/) that uses the .prc and generates a list of available repos + their clone url.
 * let the existing script call this python script in case it can't find the directory you want to move to.

Potential problems: authentication trying to retrieve data from gitlab. We'll have to dive into the web console and see if there's some headers we can send along for authentication. (this info could be stored in .prc) We can always test with github first though...

**Comment by HerrSubset** [comment]
Got a super basic version workin for github with following code:

Updated p function:
```bash
function p {
    cd $PROJECTS_DIR/$1 2> /dev/null
    if [ $? -ne 0 ]; then
        echo "Project directory not found. Will look in git repos."
        read -p "Press enter to continue, CTRL^C to exit"
        REPO=`listRepos $1`

        if [ $? -eq 0 ]; then
            cd $PROJECTS_DIR
            git clone $REPO $1
            cd $PROJECTS_DIR/$1
        else
            echo "ERROR: No repository found for $1"
        fi
    fi
}
```

Python 3 script for retrieving the repo url. You'll have to `pip install beautifulsoup4` in order to run it.
```python
#!/usr/bin/python
import sys
from bs4 import BeautifulSoup
import urllib.request

target = sys.argv[1]
url = "https://github.com/HerrSubset?tab=repositories"
fp = urllib.request.urlopen(url)
html = fp.read().decode("utf8")
fp.close()

soup = BeautifulSoup(html, 'html.parser')
repos = soup.find_all('h3')

for repo in repos:
    if repo.a.text.strip().lower() == target.lower():
        repo_url = "https://github.com" + repo.a['href'] + '.git'
        print(repo_url.lower())
        exit(0)

exit(1)
```

**Comment by deVinnnie** [comment]
Added in d39cee753d37e93bad3cd113404d811c83f934e0
